
server:
  port: 8087
spring:
  application:
    name: study-geteway-zuuls


eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


main:
  allow-bean-definition-overriding: true


zuul:
  routes:
    user-route:
      path: /feigh/**
      service-id: study-consumer-movie-feigh
    user-route1:
      path: /user/**
      service-id: study-provider-user

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000