spring:
  application:
    name: study-discovery-eureka-colony

server:
  port: 8761
eureka:
  instance:
    # 指定当profile=peer1时，主机名是peer1
    hostname: peer1
  client:
    service-url:
      # 将自己注册到peer1、peer2这个Eureka上面去
      defaultZone:  http://peer2:8762/eureka/,http://peer1:8761/eureka/
